name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish BlazorPages.csproj --configuration Release
    
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        personal_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: bin/Release/net6.0/publish/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
    
